### ISSUE TITLE
Bug: Can't Pass Response.send as a callback?

### ISSUE THREAD

**Issue by cycomachead** [github/hubot#1088]
Sometime (I believe 2.15, with middleware) recently, I stopped being able to pass around the `Response.send` method as a callback. Currently we have code like this:

``` js
    robot.respond(/listener/i, {id: ''}, function(resp) {
        // Do some stuff
        msg.send('Doing Stuff...');
        doAsyncThing(msg.send, ['Assignments Cache Refreshed']);
    });

function doAsyncThing(cb, args) {
    // yady-yady-ya
   if (cb) {
       cb.apply(null, args);
   }
}
```

The immediate fix is to wrap `resp.send` in a function, as seen here:
https://github.com/cs10/Alonzo/commit/9d9a92d4e7e37a3ab88798d28fb4d35b05bb4c15

However, without that there is a weird stack trace:

```
TypeError: Cannot read property 'apply' of undefined
  at Response.send (/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/hubot/src/response.coffee:24:5, <js>:22:36)
  at /Users/Michael/Dropbox/Projects/CS10/Alonzo/scripts/cs10/cs10-checkoffs.js:213:26
  at Request._callback (/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/node-canvas-lms/src/canvas.js:40:16)
  at Request.self.callback (/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/node-canvas-lms/node_modules/request/request.js:198:22)
  at emitTwo (events.js:87:13)
  at Request.emit (events.js:172:7)
  at Request.<anonymous> (/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/node-canvas-lms/node_modules/request/request.js:1082:10)
  at emitOne (events.js:82:20)
  at Request.emit (events.js:169:7)
  at IncomingMessage.<anonymous> (/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/node-canvas-lms/node_modules/request/request.js:1009:12)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:903:12)
  at doNTCallback2 (node.js:439:9)
  at process._tickCallback (node.js:353:17)
```

I've been trying to debug the middleware section of Hubot, but I'm not that comfortable with the code, and haven't really turned up anything. `resp.send` is definitely a function stuff, but I can't seen to be able to call `apply` on it.

Thanks for the help!

CC: @aaaschmitt

**Comment by tombell** [comment]
You called the param `resp` not `msg` in `robot.respond(/listener/i, {id: ''}, function(resp) {`

**Comment by cycomachead** [comment]
Sorry that was my bad when copying over code. In my actual Hubot they are the same variable. If I log reap.send it still shows up as a function. When I try to use apply that's when I get an error. 

- Michael
From a small keyboard. Sorry for typos.

**Comment by technicalpickles** [comment]
I've tried reading this over a few times, and having a hard time what you are trying to do. Are you saying you want a callback for `Response.send`, ie to know when it succeeded, or you are passing `Response.send` as a callback for something else?

Could you up with the smallest code sample that exposes the problem you are running into? And you only see this with after 2.15, but it works in versions before it?

That aside, I have a feeling you are running into problems with asynchronous functions and scoping, along the lines described in http://stackoverflow.com/questions/14220321/how-do-i-return-the-response-from-an-asynchronous-call/14220323#14220323 (with more links in the accepted answer).

**Comment by cycomachead** [comment]
I'll try to distill the code down when I get a chance. Thanks for the link! I'll take a look.

**Comment by bkeepers** [comment]
Closing as stale. @cycomachead let us know if this is still an issue.
