### ISSUE TITLE
yo hubot install error OSX 10.11.2

### ISSUE THREAD

**Issue by chrispeterson3** [github/hubot#1124]
`yo hubot` generator is throwing this error on OSX 10.11.2

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/Users/chrispeterson/.node/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.3
npm ERR! code ENOSELF

npm ERR! Refusing to install hubot as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chrispeterson/Projects/hubot/npm-debug.log
```

**log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.2.0/bin/node',
1 verbose cli   '/Users/chrispeterson/.node/bin/npm',
1 verbose cli   'install',
1 verbose cli   'hubot',
1 verbose cli   'hubot-scripts',
1 verbose cli   'hubot-diagnostics',
1 verbose cli   'hubot-help',
1 verbose cli   'hubot-heroku-keepalive',
1 verbose cli   'hubot-google-images',
1 verbose cli   'hubot-google-translate',
1 verbose cli   'hubot-pugme',
1 verbose cli   'hubot-maps',
1 verbose cli   'hubot-redis-brain',
1 verbose cli   'hubot-rules',
1 verbose cli   'hubot-shipit',
1 verbose cli   'hubot-slack',
1 verbose cli   '--save' ]
2 info using npm@3.5.3
3 info using node@v5.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData hubot
8 silly fetchPackageMetaData hubot-scripts
9 silly fetchPackageMetaData hubot-diagnostics
10 silly fetchPackageMetaData hubot-help
11 silly fetchPackageMetaData hubot-heroku-keepalive
12 silly fetchPackageMetaData hubot-google-images
13 silly fetchPackageMetaData hubot-google-translate
14 silly fetchPackageMetaData hubot-pugme
15 silly fetchPackageMetaData hubot-maps
16 silly fetchPackageMetaData hubot-redis-brain
17 silly fetchPackageMetaData hubot-rules
18 silly fetchPackageMetaData hubot-shipit
19 silly fetchPackageMetaData hubot-slack
20 silly fetchNamedPackageData hubot
21 silly mapToRegistry name hubot
22 silly mapToRegistry using default registry
23 silly mapToRegistry registry https://registry.npmjs.org/
24 silly mapToRegistry uri https://registry.npmjs.org/hubot
25 silly fetchNamedPackageData hubot-scripts
26 silly mapToRegistry name hubot-scripts
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry uri https://registry.npmjs.org/hubot-scripts
30 silly fetchNamedPackageData hubot-diagnostics
31 silly mapToRegistry name hubot-diagnostics
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/hubot-diagnostics
35 silly fetchNamedPackageData hubot-help
36 silly mapToRegistry name hubot-help
37 silly mapToRegistry using default registry
38 silly mapToRegistry registry https://registry.npmjs.org/
39 silly mapToRegistry uri https://registry.npmjs.org/hubot-help
40 silly fetchNamedPackageData hubot-heroku-keepalive
41 silly mapToRegistry name hubot-heroku-keepalive
42 silly mapToRegistry using default registry
43 silly mapToRegistry registry https://registry.npmjs.org/
44 silly mapToRegistry uri https://registry.npmjs.org/hubot-heroku-keepalive
45 silly fetchNamedPackageData hubot-google-images
46 silly mapToRegistry name hubot-google-images
47 silly mapToRegistry using default registry
48 silly mapToRegistry registry https://registry.npmjs.org/
49 silly mapToRegistry uri https://registry.npmjs.org/hubot-google-images
50 silly fetchNamedPackageData hubot-google-translate
51 silly mapToRegistry name hubot-google-translate
52 silly mapToRegistry using default registry
53 silly mapToRegistry registry https://registry.npmjs.org/
54 silly mapToRegistry uri https://registry.npmjs.org/hubot-google-translate
55 silly fetchNamedPackageData hubot-pugme
56 silly mapToRegistry name hubot-pugme
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry https://registry.npmjs.org/
59 silly mapToRegistry uri https://registry.npmjs.org/hubot-pugme
60 silly fetchNamedPackageData hubot-maps
61 silly mapToRegistry name hubot-maps
62 silly mapToRegistry using default registry
63 silly mapToRegistry registry https://registry.npmjs.org/
64 silly mapToRegistry uri https://registry.npmjs.org/hubot-maps
65 silly fetchNamedPackageData hubot-redis-brain
66 silly mapToRegistry name hubot-redis-brain
67 silly mapToRegistry using default registry
68 silly mapToRegistry registry https://registry.npmjs.org/
69 silly mapToRegistry uri https://registry.npmjs.org/hubot-redis-brain
70 silly fetchNamedPackageData hubot-rules
71 silly mapToRegistry name hubot-rules
72 silly mapToRegistry using default registry
73 silly mapToRegistry registry https://registry.npmjs.org/
74 silly mapToRegistry uri https://registry.npmjs.org/hubot-rules
75 silly fetchNamedPackageData hubot-shipit
76 silly mapToRegistry name hubot-shipit
77 silly mapToRegistry using default registry
78 silly mapToRegistry registry https://registry.npmjs.org/
79 silly mapToRegistry uri https://registry.npmjs.org/hubot-shipit
80 silly fetchNamedPackageData hubot-slack
81 silly mapToRegistry name hubot-slack
82 silly mapToRegistry using default registry
83 silly mapToRegistry registry https://registry.npmjs.org/
84 silly mapToRegistry uri https://registry.npmjs.org/hubot-slack
85 verbose request uri https://registry.npmjs.org/hubot
86 verbose request no auth needed
87 info attempt registry request try #1 at 7:32:01 PM
88 verbose request using bearer token for auth
89 verbose request id f9abd5006ff52598
90 verbose etag "GCE1F2NPHENP1EDWKO3GDVVH"
91 http request GET https://registry.npmjs.org/hubot
92 verbose request uri https://registry.npmjs.org/hubot-scripts
93 verbose request no auth needed
94 info attempt registry request try #1 at 7:32:01 PM
95 verbose request using bearer token for auth
96 verbose etag "E24R8AKLMIX5ZONB9MARWTF31"
97 http request GET https://registry.npmjs.org/hubot-scripts
98 verbose request uri https://registry.npmjs.org/hubot-diagnostics
99 verbose request no auth needed
100 info attempt registry request try #1 at 7:32:01 PM
101 verbose request using bearer token for auth
102 verbose etag "106XAJRQ3U3QEUCO9KTFI2EDN"
103 http request GET https://registry.npmjs.org/hubot-diagnostics
104 verbose request uri https://registry.npmjs.org/hubot-help
105 verbose request no auth needed
106 info attempt registry request try #1 at 7:32:01 PM
107 verbose request using bearer token for auth
108 verbose etag "7XIGN878YI6BPH51O0QXVCWM1"
109 http request GET https://registry.npmjs.org/hubot-help
110 verbose request uri https://registry.npmjs.org/hubot-heroku-keepalive
111 verbose request no auth needed
112 info attempt registry request try #1 at 7:32:01 PM
113 verbose request using bearer token for auth
114 verbose etag "8NR4W09OH3QYSTI17CGZSEF3W"
115 http request GET https://registry.npmjs.org/hubot-heroku-keepalive
116 verbose request uri https://registry.npmjs.org/hubot-google-images
117 verbose request no auth needed
118 info attempt registry request try #1 at 7:32:01 PM
119 verbose request using bearer token for auth
120 verbose etag "6E7ETP2NY8LT9RQFJYU3DBPNF"
121 http request GET https://registry.npmjs.org/hubot-google-images
122 verbose request uri https://registry.npmjs.org/hubot-maps
123 verbose request no auth needed
124 info attempt registry request try #1 at 7:32:01 PM
125 verbose request using bearer token for auth
126 verbose etag "6IHH2K69FPEROF9F42PVBQ035"
127 http request GET https://registry.npmjs.org/hubot-maps
128 verbose request uri https://registry.npmjs.org/hubot-google-translate
129 verbose request no auth needed
130 info attempt registry request try #1 at 7:32:01 PM
131 verbose request using bearer token for auth
132 verbose etag "1AI1GKUOV2AZHP1ZPKKXLOR1H"
133 http request GET https://registry.npmjs.org/hubot-google-translate
134 verbose request uri https://registry.npmjs.org/hubot-pugme
135 verbose request no auth needed
136 info attempt registry request try #1 at 7:32:01 PM
137 verbose request using bearer token for auth
138 verbose etag "EEKN1R8NSDUC4HZXWND71MDFM"
139 http request GET https://registry.npmjs.org/hubot-pugme
140 verbose request uri https://registry.npmjs.org/hubot-rules
141 verbose request no auth needed
142 info attempt registry request try #1 at 7:32:01 PM
143 verbose request using bearer token for auth
144 verbose etag "BMPTBVMMPVBT70MAM9AGAPBP9"
145 http request GET https://registry.npmjs.org/hubot-rules
146 verbose request uri https://registry.npmjs.org/hubot-redis-brain
147 verbose request no auth needed
148 info attempt registry request try #1 at 7:32:01 PM
149 verbose request using bearer token for auth
150 verbose etag "A09HRQQWT6V5UGFY47JCUP9UQ"
151 http request GET https://registry.npmjs.org/hubot-redis-brain
152 verbose request uri https://registry.npmjs.org/hubot-shipit
153 verbose request no auth needed
154 info attempt registry request try #1 at 7:32:01 PM
155 verbose request using bearer token for auth
156 verbose etag "9IPK77V8RI5KCWNN4T6ICXAGY"
157 http request GET https://registry.npmjs.org/hubot-shipit
158 verbose request uri https://registry.npmjs.org/hubot-slack
159 verbose request no auth needed
160 info attempt registry request try #1 at 7:32:01 PM
161 verbose request using bearer token for auth
162 verbose etag "17XCJF62FGLZ6Q791F32EU39X"
163 http request GET https://registry.npmjs.org/hubot-slack
164 http 304 https://registry.npmjs.org/hubot-redis-brain
165 verbose headers { 'cache-control': 'max-age=300',
165 verbose headers   'accept-ranges': 'bytes',
165 verbose headers   date: 'Wed, 27 Jan 2016 01:32:00 GMT',
165 verbose headers   via: '1.1 varnish',
165 verbose headers   connection: 'keep-alive',
165 verbose headers   'x-served-by': 'cache-ord1732-ORD',
165 verbose headers   'x-cache': 'MISS',
165 verbose headers   'x-cache-hits': '0',
165 verbose headers   'x-timer': 'S1453858320.952601,VS0,VE37' }
166 silly get cb [ 304,
166 silly get   { 'cache-control': 'max-age=300',
166 silly get     'accept-ranges': 'bytes',
166 silly get     date: 'Wed, 27 Jan 2016 01:32:00 GMT',
166 silly get     via: '1.1 varnish',
166 silly get     connection: 'keep-alive',
166 silly get     'x-served-by': 'cache-ord1732-ORD',
166 silly get     'x-cache': 'MISS',
166 silly get     'x-cache-hits': '0',
166 silly get     'x-timer': 'S1453858320.952601,VS0,VE37' } ]
167 verbose etag https://registry.npmjs.org/hubot-redis-brain from cache
168 verbose get saving hubot-redis-brain to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-redis-brain/.cache.json
169 http 304 https://registry.npmjs.org/hubot-help
170 verbose headers { 'cache-control': 'max-age=300',
170 verbose headers   'accept-ranges': 'bytes',
170 verbose headers   date: 'Wed, 27 Jan 2016 01:32:00 GMT',
170 verbose headers   via: '1.1 varnish',
170 verbose headers   connection: 'keep-alive',
170 verbose headers   'x-served-by': 'cache-ord1730-ORD',
170 verbose headers   'x-cache': 'MISS',
170 verbose headers   'x-cache-hits': '0',
170 verbose headers   'x-timer': 'S1453858320.951362,VS0,VE45' }
171 silly get cb [ 304,
171 silly get   { 'cache-control': 'max-age=300',
171 silly get     'accept-ranges': 'bytes',
171 silly get     date: 'Wed, 27 Jan 2016 01:32:00 GMT',
171 silly get     via: '1.1 varnish',
171 silly get     connection: 'keep-alive',
171 silly get     'x-served-by': 'cache-ord1730-ORD',
171 silly get     'x-cache': 'MISS',
171 silly get     'x-cache-hits': '0',
171 silly get     'x-timer': 'S1453858320.951362,VS0,VE45' } ]
172 verbose etag https://registry.npmjs.org/hubot-help from cache
173 verbose get saving hubot-help to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-help/.cache.json
174 http 304 https://registry.npmjs.org/hubot-slack
175 verbose headers { 'cache-control': 'max-age=300',
175 verbose headers   'accept-ranges': 'bytes',
175 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
175 verbose headers   via: '1.1 varnish',
175 verbose headers   connection: 'keep-alive',
175 verbose headers   'x-served-by': 'cache-ord1720-ORD',
175 verbose headers   'x-cache': 'MISS',
175 verbose headers   'x-cache-hits': '0',
175 verbose headers   'x-timer': 'S1453858320.956666,VS0,VE74' }
176 silly get cb [ 304,
176 silly get   { 'cache-control': 'max-age=300',
176 silly get     'accept-ranges': 'bytes',
176 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
176 silly get     via: '1.1 varnish',
176 silly get     connection: 'keep-alive',
176 silly get     'x-served-by': 'cache-ord1720-ORD',
176 silly get     'x-cache': 'MISS',
176 silly get     'x-cache-hits': '0',
176 silly get     'x-timer': 'S1453858320.956666,VS0,VE74' } ]
177 verbose etag https://registry.npmjs.org/hubot-slack from cache
178 verbose get saving hubot-slack to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-slack/.cache.json
179 http 304 https://registry.npmjs.org/hubot-rules
180 verbose headers { 'cache-control': 'max-age=300',
180 verbose headers   'accept-ranges': 'bytes',
180 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
180 verbose headers   via: '1.1 varnish',
180 verbose headers   connection: 'keep-alive',
180 verbose headers   'x-served-by': 'cache-ord1720-ORD',
180 verbose headers   'x-cache': 'MISS',
180 verbose headers   'x-cache-hits': '0',
180 verbose headers   'x-timer': 'S1453858320.956648,VS0,VE73' }
181 silly get cb [ 304,
181 silly get   { 'cache-control': 'max-age=300',
181 silly get     'accept-ranges': 'bytes',
181 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
181 silly get     via: '1.1 varnish',
181 silly get     connection: 'keep-alive',
181 silly get     'x-served-by': 'cache-ord1720-ORD',
181 silly get     'x-cache': 'MISS',
181 silly get     'x-cache-hits': '0',
181 silly get     'x-timer': 'S1453858320.956648,VS0,VE73' } ]
182 verbose etag https://registry.npmjs.org/hubot-rules from cache
183 verbose get saving hubot-rules to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-rules/.cache.json
184 http 304 https://registry.npmjs.org/hubot-diagnostics
185 verbose headers { 'cache-control': 'max-age=300',
185 verbose headers   'accept-ranges': 'bytes',
185 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
185 verbose headers   via: '1.1 varnish',
185 verbose headers   connection: 'keep-alive',
185 verbose headers   'x-served-by': 'cache-ord1735-ORD',
185 verbose headers   'x-cache': 'MISS',
185 verbose headers   'x-cache-hits': '0',
185 verbose headers   'x-timer': 'S1453858320.947044,VS0,VE146' }
186 silly get cb [ 304,
186 silly get   { 'cache-control': 'max-age=300',
186 silly get     'accept-ranges': 'bytes',
186 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
186 silly get     via: '1.1 varnish',
186 silly get     connection: 'keep-alive',
186 silly get     'x-served-by': 'cache-ord1735-ORD',
186 silly get     'x-cache': 'MISS',
186 silly get     'x-cache-hits': '0',
186 silly get     'x-timer': 'S1453858320.947044,VS0,VE146' } ]
187 verbose etag https://registry.npmjs.org/hubot-diagnostics from cache
188 verbose get saving hubot-diagnostics to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-diagnostics/.cache.json
189 http 304 https://registry.npmjs.org/hubot-heroku-keepalive
190 verbose headers { 'cache-control': 'max-age=300',
190 verbose headers   'accept-ranges': 'bytes',
190 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
190 verbose headers   via: '1.1 varnish',
190 verbose headers   connection: 'keep-alive',
190 verbose headers   'x-served-by': 'cache-ord1733-ORD',
190 verbose headers   'x-cache': 'MISS',
190 verbose headers   'x-cache-hits': '0',
190 verbose headers   'x-timer': 'S1453858320.949223,VS0,VE149' }
191 silly get cb [ 304,
191 silly get   { 'cache-control': 'max-age=300',
191 silly get     'accept-ranges': 'bytes',
191 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
191 silly get     via: '1.1 varnish',
191 silly get     connection: 'keep-alive',
191 silly get     'x-served-by': 'cache-ord1733-ORD',
191 silly get     'x-cache': 'MISS',
191 silly get     'x-cache-hits': '0',
191 silly get     'x-timer': 'S1453858320.949223,VS0,VE149' } ]
192 verbose etag https://registry.npmjs.org/hubot-heroku-keepalive from cache
193 verbose get saving hubot-heroku-keepalive to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-heroku-keepalive/.cache.json
194 http 304 https://registry.npmjs.org/hubot
195 verbose headers { 'cache-control': 'max-age=300',
195 verbose headers   'accept-ranges': 'bytes',
195 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
195 verbose headers   via: '1.1 varnish',
195 verbose headers   connection: 'keep-alive',
195 verbose headers   'x-served-by': 'cache-ord1731-ORD',
195 verbose headers   'x-cache': 'MISS',
195 verbose headers   'x-cache-hits': '0',
195 verbose headers   'x-timer': 'S1453858320.948697,VS0,VE257' }
196 silly get cb [ 304,
196 silly get   { 'cache-control': 'max-age=300',
196 silly get     'accept-ranges': 'bytes',
196 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
196 silly get     via: '1.1 varnish',
196 silly get     connection: 'keep-alive',
196 silly get     'x-served-by': 'cache-ord1731-ORD',
196 silly get     'x-cache': 'MISS',
196 silly get     'x-cache-hits': '0',
196 silly get     'x-timer': 'S1453858320.948697,VS0,VE257' } ]
197 verbose etag https://registry.npmjs.org/hubot from cache
198 verbose get saving hubot to /Users/chrispeterson/.npm/registry.npmjs.org/hubot/.cache.json
199 http 304 https://registry.npmjs.org/hubot-scripts
200 verbose headers { 'cache-control': 'max-age=300',
200 verbose headers   'accept-ranges': 'bytes',
200 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
200 verbose headers   via: '1.1 varnish',
200 verbose headers   connection: 'keep-alive',
200 verbose headers   'x-served-by': 'cache-ord1727-ORD',
200 verbose headers   'x-cache': 'MISS',
200 verbose headers   'x-cache-hits': '0',
200 verbose headers   'x-timer': 'S1453858320.932455,VS0,VE304' }
201 silly get cb [ 304,
201 silly get   { 'cache-control': 'max-age=300',
201 silly get     'accept-ranges': 'bytes',
201 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
201 silly get     via: '1.1 varnish',
201 silly get     connection: 'keep-alive',
201 silly get     'x-served-by': 'cache-ord1727-ORD',
201 silly get     'x-cache': 'MISS',
201 silly get     'x-cache-hits': '0',
201 silly get     'x-timer': 'S1453858320.932455,VS0,VE304' } ]
202 verbose etag https://registry.npmjs.org/hubot-scripts from cache
203 verbose get saving hubot-scripts to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-scripts/.cache.json
204 http 304 https://registry.npmjs.org/hubot-pugme
205 verbose headers { 'cache-control': 'max-age=300',
205 verbose headers   'accept-ranges': 'bytes',
205 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
205 verbose headers   via: '1.1 varnish',
205 verbose headers   connection: 'keep-alive',
205 verbose headers   'x-served-by': 'cache-ord1721-ORD',
205 verbose headers   'x-cache': 'MISS',
205 verbose headers   'x-cache-hits': '0',
205 verbose headers   'x-timer': 'S1453858320.951673,VS0,VE299' }
206 silly get cb [ 304,
206 silly get   { 'cache-control': 'max-age=300',
206 silly get     'accept-ranges': 'bytes',
206 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
206 silly get     via: '1.1 varnish',
206 silly get     connection: 'keep-alive',
206 silly get     'x-served-by': 'cache-ord1721-ORD',
206 silly get     'x-cache': 'MISS',
206 silly get     'x-cache-hits': '0',
206 silly get     'x-timer': 'S1453858320.951673,VS0,VE299' } ]
207 verbose etag https://registry.npmjs.org/hubot-pugme from cache
208 verbose get saving hubot-pugme to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-pugme/.cache.json
209 http 304 https://registry.npmjs.org/hubot-shipit
210 verbose headers { 'cache-control': 'max-age=300',
210 verbose headers   'accept-ranges': 'bytes',
210 verbose headers   date: 'Wed, 27 Jan 2016 01:32:01 GMT',
210 verbose headers   via: '1.1 varnish',
210 verbose headers   connection: 'keep-alive',
210 verbose headers   'x-served-by': 'cache-ord1724-ORD',
210 verbose headers   'x-cache': 'MISS',
210 verbose headers   'x-cache-hits': '0',
210 verbose headers   'x-timer': 'S1453858320.951038,VS0,VE303' }
211 silly get cb [ 304,
211 silly get   { 'cache-control': 'max-age=300',
211 silly get     'accept-ranges': 'bytes',
211 silly get     date: 'Wed, 27 Jan 2016 01:32:01 GMT',
211 silly get     via: '1.1 varnish',
211 silly get     connection: 'keep-alive',
211 silly get     'x-served-by': 'cache-ord1724-ORD',
211 silly get     'x-cache': 'MISS',
211 silly get     'x-cache-hits': '0',
211 silly get     'x-timer': 'S1453858320.951038,VS0,VE303' } ]
212 verbose etag https://registry.npmjs.org/hubot-shipit from cache
213 verbose get saving hubot-shipit to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-shipit/.cache.json
214 http 304 https://registry.npmjs.org/hubot-maps
215 verbose headers { 'cache-control': 'max-age=300',
215 verbose headers   'accept-ranges': 'bytes',
215 verbose headers   date: 'Wed, 27 Jan 2016 01:32:02 GMT',
215 verbose headers   via: '1.1 varnish',
215 verbose headers   connection: 'keep-alive',
215 verbose headers   'x-served-by': 'cache-ord1726-ORD',
215 verbose headers   'x-cache': 'MISS',
215 verbose headers   'x-cache-hits': '0',
215 verbose headers   'x-timer': 'S1453858321.991891,VS0,VE36' }
216 silly get cb [ 304,
216 silly get   { 'cache-control': 'max-age=300',
216 silly get     'accept-ranges': 'bytes',
216 silly get     date: 'Wed, 27 Jan 2016 01:32:02 GMT',
216 silly get     via: '1.1 varnish',
216 silly get     connection: 'keep-alive',
216 silly get     'x-served-by': 'cache-ord1726-ORD',
216 silly get     'x-cache': 'MISS',
216 silly get     'x-cache-hits': '0',
216 silly get     'x-timer': 'S1453858321.991891,VS0,VE36' } ]
217 verbose etag https://registry.npmjs.org/hubot-maps from cache
218 verbose get saving hubot-maps to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-maps/.cache.json
219 http 304 https://registry.npmjs.org/hubot-google-translate
220 verbose headers { 'cache-control': 'max-age=300',
220 verbose headers   'accept-ranges': 'bytes',
220 verbose headers   date: 'Wed, 27 Jan 2016 01:32:02 GMT',
220 verbose headers   via: '1.1 varnish',
220 verbose headers   connection: 'keep-alive',
220 verbose headers   'x-served-by': 'cache-ord1723-ORD',
220 verbose headers   'x-cache': 'MISS',
220 verbose headers   'x-cache-hits': '0',
220 verbose headers   'x-timer': 'S1453858321.985124,VS0,VE275' }
221 silly get cb [ 304,
221 silly get   { 'cache-control': 'max-age=300',
221 silly get     'accept-ranges': 'bytes',
221 silly get     date: 'Wed, 27 Jan 2016 01:32:02 GMT',
221 silly get     via: '1.1 varnish',
221 silly get     connection: 'keep-alive',
221 silly get     'x-served-by': 'cache-ord1723-ORD',
221 silly get     'x-cache': 'MISS',
221 silly get     'x-cache-hits': '0',
221 silly get     'x-timer': 'S1453858321.985124,VS0,VE275' } ]
222 verbose etag https://registry.npmjs.org/hubot-google-translate from cache
223 verbose get saving hubot-google-translate to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-google-translate/.cache.json
224 http 304 https://registry.npmjs.org/hubot-google-images
225 verbose headers { 'cache-control': 'max-age=300',
225 verbose headers   'accept-ranges': 'bytes',
225 verbose headers   date: 'Wed, 27 Jan 2016 01:32:02 GMT',
225 verbose headers   via: '1.1 varnish',
225 verbose headers   connection: 'keep-alive',
225 verbose headers   'x-served-by': 'cache-ord1734-ORD',
225 verbose headers   'x-cache': 'MISS',
225 verbose headers   'x-cache-hits': '0',
225 verbose headers   'x-timer': 'S1453858321.976098,VS0,VE312' }
226 silly get cb [ 304,
226 silly get   { 'cache-control': 'max-age=300',
226 silly get     'accept-ranges': 'bytes',
226 silly get     date: 'Wed, 27 Jan 2016 01:32:02 GMT',
226 silly get     via: '1.1 varnish',
226 silly get     connection: 'keep-alive',
226 silly get     'x-served-by': 'cache-ord1734-ORD',
226 silly get     'x-cache': 'MISS',
226 silly get     'x-cache-hits': '0',
226 silly get     'x-timer': 'S1453858321.976098,VS0,VE312' } ]
227 verbose etag https://registry.npmjs.org/hubot-google-images from cache
228 verbose get saving hubot-google-images to /Users/chrispeterson/.npm/registry.npmjs.org/hubot-google-images/.cache.json
229 silly install normalizeTree
230 silly loadCurrentTree Finishing
231 silly loadIdealTree Starting
232 silly install loadIdealTree
233 silly cloneCurrentTree Starting
234 silly install cloneCurrentTreeToIdealTree
235 silly cloneCurrentTree Finishing
236 silly loadShrinkwrap Starting
237 silly install loadShrinkwrap
238 silly loadShrinkwrap Finishing
239 silly loadAllDepsIntoIdealTree Starting
240 silly install loadAllDepsIntoIdealTree
241 silly rollbackFailedOptional Starting
242 silly rollbackFailedOptional Finishing
243 silly runTopLevelLifecycles Starting
244 silly runTopLevelLifecycles Finishing
245 silly install printInstalled
246 verbose stack Error: Refusing to install hubot as a dependency of itself
246 verbose stack     at checkSelf (/Users/chrispeterson/.node/lib/node_modules/npm/lib/install/validate-args.js:40:14)
246 verbose stack     at Array.<anonymous> (/Users/chrispeterson/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
246 verbose stack     at LOOP (/Users/chrispeterson/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
246 verbose stack     at chain (/Users/chrispeterson/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
246 verbose stack     at /Users/chrispeterson/.node/lib/node_modules/npm/lib/install/validate-args.js:15:5
246 verbose stack     at /Users/chrispeterson/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
246 verbose stack     at Array.forEach (native)
246 verbose stack     at /Users/chrispeterson/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
246 verbose stack     at Array.forEach (native)
246 verbose stack     at asyncMap (/Users/chrispeterson/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
247 verbose cwd /Users/chrispeterson/Projects/hubot
248 error Darwin 15.2.0
249 error argv "/usr/local/Cellar/node/5.2.0/bin/node" "/Users/chrispeterson/.node/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
250 error node v5.2.0
251 error npm  v3.5.3
252 error code ENOSELF
253 error Refusing to install hubot as a dependency of itself
254 error If you need help, you may report this error at:
254 error     <https://github.com/npm/npm/issues>
255 verbose exit [ 1, true ]

```

**Comment by SenHeng** [comment]
I'm getting the same error on OSX 10.11.3.

What I've discovered is that hubot refuses to install if the folder is named `hubot`.
It installs fine in `bot`.

**Comment by chrispeterson3** [comment]
Yes that is correct. Same issue with me. Thanks!

**Comment by timbroder** [comment]
Thanks @SenHeng!

**Comment by goldo** [comment]
Still the same issue with mac os sierra.. thanks @SenHeng
