### ISSUE TITLE
how to resolve this problem   thanks

### ISSUE THREAD

**Issue by fanhengxing** [github/hubot#1137]
i install like this in centos7 and user is root：
https://hubot.github.com/docs/
 1.npm install -g yo generator-hubot
2.mkdir myhubot
3.cd myhubot
4.yo hubot
then   error：
Error: EACCES, permission denied '/root/.config'
    at Object.fs.mkdirSync (fs.js:654:18)
    at sync (/usr/lib/node_modules/yo/node_modules/configstore/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/yo/node_modules/configstore/node_modules/mkdirp/index.js:77:24)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:38:13)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:163:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by marceloslacerda** [comment]
it's a bug with yo
https://github.com/yeoman/yeoman.github.io/issues/282#issuecomment-64543114
You need to chown all directories that throw that error. 😣

**Comment by HerrmannHinz** [comment]
in case your try to run this in a docker container, check this comment:

https://github.com/keystonejs/keystone/issues/1566#issuecomment-217736880

**Comment by bkeepers** [comment]
Looks like this has been answered. Let us know if it hasn't.
