### ISSUE TITLE
Hubot tries to unlock files that have not been locked

### ISSUE THREAD

**Issue by colt05** [github/hubot#1208]
Hello!
I have been trying to use Hubot and this error occurs:

```
npm ERR! Error: Attempt to unlock hubot, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-scripts, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-diagnostics, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-help, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-heroku-keepalive, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-google-images, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-google-translate, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-pugme, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-maps, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-redis-brain, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-rules, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-shipit, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! Error: Attempt to unlock hubot-slack, which hasn't been locked
npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-042stab116.1
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-slack" "--save"
npm ERR! cwd /root/myhubot
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/myhubot/npm-debug.log
npm ERR! not ok code 0
```

Any way to fix this? Thanks!

**Comment by mose** [comment]
This seems to be a permission issue, described in http://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been

In your case maybe it would be (as you launch it with root account and use system-wide node modules):

    sudo chown -R $USER /usr/lib/node_modules

As a side-note, it's usually advised to launch hubot with a non-root user.
