### ISSUE TITLE
ERROR Error loading scripts from npm package - TypeError: object is not a function

### ISSUE THREAD

**Issue by traimo** [github/hubot#1242]
I'm having trouble installing HUBOT-FRESHDESK.  I updated package.json and external-scripts.json but heroku crashes with this error.  Can you please help?  Thank you,

2016-10-02T01:46:44.481448+00:00 heroku[api]: Deploy a353e02 by traimo@erp-is.com
2016-10-02T01:46:44.481501+00:00 heroku[api]: Release v19 created by traimo@erp-is.com
2016-10-02T01:46:44.657771+00:00 heroku[slug-compiler]: Slug compilation started
2016-10-02T01:46:44.657776+00:00 heroku[slug-compiler]: Slug compilation finished
2016-10-02T01:46:44.733353+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-02T01:46:46.556423+00:00 heroku[web.1]: Starting process with command `bin/hubot -a slack`
2016-10-02T01:46:55.323775+00:00 app[web.1]: [Sun Oct 02 2016 01:46:55 GMT+0000 (UTC)] INFO Logged in as erpbot of ERP-IS
2016-10-02T01:46:55.360760+00:00 app[web.1]: [Sun Oct 02 2016 01:46:55 GMT+0000 (UTC)] INFO Slack client now connected
2016-10-02T01:46:55.510628+00:00 app[web.1]: [Sun Oct 02 2016 01:46:55 GMT+0000 (UTC)] ERROR Error loading scripts from npm package - TypeError: object is not a function
2016-10-02T01:46:55.510637+00:00 app[web.1]:   at Robot.loadExternalScripts (/app/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
2016-10-02T01:46:55.510645+00:00 app[web.1]:   at /app/node_modules/hubot/bin/hubot:152:11, <js>:159:26
2016-10-02T01:46:55.510646+00:00 app[web.1]:   at fs.js:272:14
2016-10-02T01:46:55.510659+00:00 app[web.1]:   at Object.oncomplete (fs.js:108:15)
2016-10-02T01:46:55.510671+00:00 app[web.1]:
2016-10-02T01:46:55.676291+00:00 heroku[web.1]: State changed from up to crashed

**Comment by mose** [comment]
It comes from the `hubot-freshdesk` plugin. It cannot work, because its `index.coffee` is empty, where it's supposed to load the script. You should open an issue on hubot-freshdesk project.

**Comment by technicalpickles** [comment]
> It comes from the hubot-freshdesk plugin. It cannot work, because its index.coffee is empty, where it's supposed to load the script. You should open an issue on hubot-freshdesk project.

Exactly this, thanks @mose 

Unfortunately, it seems like that script never worked, and hasn't been updated in 3 years.
