### ISSUE TITLE
Azure deployment into an App Service fails with stdin error

### ISSUE THREAD

**Issue by jonathanrelf** [github/hubot#1252]
Following the instructions to deploy Hubot 2.19.0 to Azure I end up with a terminal exception being thrown meaning Hubot is unresponsive. (exception pasted at the end)
It's being hosted on a Standard 1 Small App Service instance. 

I followed [Jason Poon's blog article](http://jasonpoon.ca/2015/06/12/how-to-deploy-hubot-in-slack-to-azure/) and had to amend some of the instructions to use the ARM model. 
(e.g. using Azure .NET CLI setting the appsettings using `azure webapp config appsettings set <RESOURCE-GROUP> <WEBAPP-NAME> HUBOT_BRAIN_AZURE_STORAGE_ACCOUNT=<BLOB_STORAGE>`
It is very similar to the Azure.md instructions in the Hubot docs. I created the App Service account using the Portal and attached my Bitbucket repository to allow continuous deployment. 

I enabled logging to determine what was going wrong by adding the following to an iisnode.yml file and added node-inspector too to see if I could determine what was causing the problem:
`loggingEnabled: true
logDirectory: iisnode
debuggingEnabled: true
debuggerExtensionDll: iisnode-inspector.dll`

[A issue on the iisnode repository](https://github.com/tjanczuk/iisnode/issues/337) suggests that maybe interceptor.js is the problem when presented with a node.js app that requires process.stdin which hubot uses by default before adding any adapters. 

Is there any way of disabling the console input built-in 'adapter' if this headless mode of hosting in Azure using IISNode is going to cause this exception?
Is anyone else having this trouble with Azure hosting? 

`Tue Oct 25 2016 02:21:22 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
Error: Implement me. Unknown stdin file type!
  at process.stdin (node.js:702:17)
  at [object Object].defaultStream (D:\home\site\wwwroot\node_modules\hubot\node_modules\cline\index.js:109:61)
  at [object Object].Cli.init (D:\home\site\wwwroot\node_modules\hubot\node_modules\cline\index.js:138:32)
  at new Cli (D:\home\site\wwwroot\node_modules\hubot\node_modules\cline\index.js:127:10)
  at module.exports (D:\home\site\wwwroot\node_modules\hubot\node_modules\cline\index.js:335:15)
  at Shell.buildCli (D:\home\site\wwwroot\node_modules\hubot\src\adapters\shell.coffee:42:12)
  at Shell.run (D:\home\site\wwwroot\node_modules\hubot\src\adapters\shell.coffee:30:6)
  at Robot.run (D:\home\site\wwwroot\node_modules\hubot\src\robot.coffee:590:14)
  at Object.<anonymous> (D:\home\site\wwwroot\node_modules\hubot\bin\hubot.coffee:168:9)
  at Object.<anonymous> (D:\home\site\wwwroot\node_modules\hubot\bin\hubot.coffee:5:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (D:\home\site\wwwroot\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (D:\home\site\wwwroot\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (D:\home\site\wwwroot\server.js:2:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (D:\Program Files (x86)\iisnode\interceptor.js:451:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3`

**Comment by technicalpickles** [comment]
Which adapter are you using? The article you linked to was using Slack.

> Is there any way of disabling the console input built-in 'adapter' if this headless mode of hosting in Azure using IISNode is going to cause this exception?

Hubot can only use one adapter at a time, with a default of the 'shell' adapter which reads from stdin. If you specify any other adapter, that is used instead.

cc @uugengiven @davidkassa @akameco as contributors to the azure documentation

**Comment by jonathanrelf** [comment]
@technicalpickles I was using the HipChat adapter and I had amended the startup script in package.json to contain:

"scripts": {
    "start": "bash ./bin/hubot -a hipchat"
  },

I realise now that this wasn't the method described of selecting an alternative adapter. I had incorrectly assumed this would work as you would with a standalone deployment of Hubot. 
I've just redeployed my Web App and used HUBOT_ADAPTER=hipchat (through the Azure Application Settings) and it's working
