### ISSUE TITLE
Getting "Cannot find module 'hubot-diagnostics'" in Production

### ISSUE THREAD

**Issue by latazzajones** [github/hubot#1257]
Hi - I'm trying to get Hubot running on Heroku and it keeps crashing with the following error: 
`ERROR Error loading scripts from npm package - Error: Cannot find module 'hubot-diagnostics'`

Here's the full tail: 
```
2016-11-02T18:11:52.247064+00:00 heroku[web.1]: State changed from crashed to starting
2016-11-02T18:11:53.413950+00:00 heroku[web.1]: Starting process with command `bin/hubot -a flowdock`
2016-11-02T18:11:57.267353+00:00 heroku[web.1]: State changed from starting to up
2016-11-02T18:11:57.397982+00:00 heroku[web.1]: Process exited with status 1
2016-11-02T18:11:57.170647+00:00 app[web.1]: [Wed Nov 02 2016 14:11:57 GMT-0400 (EDT)] INFO Ignoring all messages from user ids 0
2016-11-02T18:11:57.243784+00:00 app[web.1]: [Wed Nov 02 2016 14:11:57 GMT-0400 (EDT)] INFO /app/scripts/trello.js is using deprecated documentation syntax
2016-11-02T18:11:57.288732+00:00 app[web.1]: [Wed Nov 02 2016 14:11:57 GMT-0400 (EDT)] ERROR Error loading scripts from npm package - Error: Cannot find module 'hubot-diagnostics'
2016-11-02T18:11:57.288734+00:00 app[web.1]:   at Function.Module._resolveFilename (module.js:338:15)
2016-11-02T18:11:57.288738+00:00 app[web.1]:   at Function.Module._load (module.js:280:25)
2016-11-02T18:11:57.288738+00:00 app[web.1]:   at Module.require (module.js:364:17)
2016-11-02T18:11:57.288739+00:00 app[web.1]:   at require (module.js:380:17)
2016-11-02T18:11:57.288740+00:00 app[web.1]:   at Robot.loadExternalScripts (/app/node_modules/hubot/src/robot.coffee:401:11, <js>:272:27)
2016-11-02T18:11:57.288741+00:00 app[web.1]:   at /app/node_modules/hubot/bin/hubot:152:11, <js>:159:26
2016-11-02T18:11:57.288741+00:00 app[web.1]:   at fs.js:272:14
2016-11-02T18:11:57.288742+00:00 app[web.1]:   at Object.oncomplete (fs.js:108:15)
```
Here's what my package.json file looks like: 
```
{
  "name": "hubot",
  "version": "0.0.0",
  "private": true,
  "author": "Y",
  "description": "Keep it cool for Fractured Atlas",
  "dependencies": {
    "cron": "^1.1.0",
    "hubot": ">= 2.5.0",
    "hubot-flowdock": "^0.7.6",
    "hubot-heroku-keepalive": "^1.0.2",
    "hubot-trello": "^0.2.0",
    "time": "^0.11.4"
  },
  "engines": {
    "node": "0.10.x"
  },
  "devDependencies": {
    "hubot-test-helper": "^1.5.0"
  }
}
```
Am I missing something obvious? I've set all the env vars in Heroku - but I guess the node modules aren't getting loaded? I'm not super familiar with node - so any advice is helpful.

**Comment by latazzajones** [comment]
I figured it out - for some reason my dependencies in `external-scripts.json` weren't being added to my package.json file when I ran npm install. So - I had to `$npm install package_name --save` for each package separately. I'm sure there's a better way to do that with npm but this worked for now.

**Comment by technicalpickles** [comment]
@latazzajones that's actually the expected workflow for right now. It's necessary to tell npm to install the package (ie `npm install --save`), and also tell hubot about it (`external-scripts.json`)

Documentation for script packages should specify this, for example https://github.com/hubot-scripts/hubot-diagnostics#installation

It isn't great to have to specify things twice, but I don't know of a better way to handle this yet.
