### ISSUE TITLE
Hubot Setup Error on "Bot Adapter" Question? 

### ISSUE THREAD

**Issue by Fire5** [github/hubot#1281]
When im setting my Hubot up, I answer my first few questions with no problem, but then when I get to the Bot Adapter, I type "? Bot adapter: campfire", and get this error:

"/usr/local/lib/node_modules/generator-hubot/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/balsalobre/Atlas/bin'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Function.sync (/usr/local/lib/node_modules/generator-hubot/node_modules/mkdirp/index.js:71:13)
    at yeoman.generators.Base.extend.writing.app (/usr/local/lib/node_modules/generator-hubot/generators/app/index.js:246:12)
    at /usr/local/lib/node_modules/generator-hubot/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:383:17)"

Help?

**Comment by mose** [comment]
Well, this is visibly a local perms issue. a `sudo chown -R $USER /home/balsalobre/Atlas` certainly did fix your problem :)
