### ISSUE TITLE
running yo gives ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by mnp** [github/hubot#1283]
Attempting to create a hubot, I get this when pressing enter or entering anything at the Owner prompt.

```
~/myhubot$ yo hubot
                     _____________________________  
                    /                             \ 
   //\              |      Extracting input for    |
  ////\    _____    |   self-replication process   |
 //////\  /_____\   \                             / 
 ======= |[^_/\_]|   /----------------------------  
  |   | _|___@@__|__                                
  +===+/  ///     \_\                               
   | |_\ /// HUBOT/\\                             
   |___/\//      /  \\                            
         \      /   +---+                            
          \____/    |   |                            
           | //|    +===+                            
            \//      |xx|                            

? Owner (User <user@example.com>) 


/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:77
    throw e;
          ^
ReferenceError: Promise is not defined
    at /home/mnp/node_modules/yeoman-environment/node_modules/run-async/index.js:24:23
    at /home/mnp/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/base.js:88:12
    at tryCatcher (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.next (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:5409:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/mnp/node_modules/yeoman-environment/node_modules/rx/dist/rx.js:1762:31)
```

My setup is unique in that it's all local: I don't have root so I installed nodejs locally in $home and then add that to path before the old busted system one.

```
$ nodejs --version
v0.10.46
$ npm --version
3.10.10
mnp@apathy:~/myhubot$ which node
/home/mnp/node/bin/node
mnp@apathy:~/myhubot$ which npm
/home/mnp/node/bin/npm
mnp@apathy:~/myhubot$ echo $PATH
/home/mnp/node_modules/.bin:/home/mnp/node/bin:/home/mnp/node_modules/.bin:/usr/local/bin:/usr/bin:/bin
```

**Comment by a-suenami** [comment]
I have same problems.

**Comment by a-suenami** [comment]
I've resolved by updating node version to recent version.

**Comment by mose** [comment]
Yes the generator require nodejs 4+
