### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by sirtow** [github/hubot#1300]
Im getting this error once in a while: "Error: request entity too large" but i cannot figure out what URI being processed or who is sending the offending request.  Any clue on how to find the URI?
Stacktrace :
Error: request entity too large:
`                              at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
                              at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
                              at emitTwo (events.js:106:13)
                              at next (/opt/hubot/node_modules/connect/lib/proto.js:174:15)
                              at Function.app.handle (/opt/hubot/node_modules/connect/lib/proto.js:182:3)
                              at Object.query [as handle] (/opt/hubot/node_modules/connect/lib/middleware/query.js:43:5)
                              at next (/opt/hubot/node_modules/connect/lib/proto.js:174:15)
                              at Object.expressInit [as handle] (/opt/hubot/node_modules/express/lib/middleware.js:30:5)
                              at next (/opt/hubot/node_modules/connect/lib/proto.js:174:15)
                              at Object.handle (/opt/hubot/node_modules/hubot/src/robot.coffee:426:7, <js>:303:16)
                              at next (/opt/hubot/node_modules/connect/lib/proto.js:174:15)
                              at Object.query [as handle] (/opt/hubot/node_modules/connect/lib/middleware/query.js:43:5)
                              at next (/opt/hubot/node_modules/connect/lib/proto.js:174:15)
                              at Object.jsonParser [as handle] (/opt/hubot/node_modules/body-parser/lib/types/json.js:121:5)
                              at read (/opt/hubot/node_modules/body-parser/lib/read.js:68:3)
                              at getRawBody (/opt/hubot/node_modules/raw-body/index.js:106:12)
                              at readStream (/opt/hubot/node_modules/raw-body/index.js:196:17)`

**Comment by mose** [comment]
Well you can launch hubot with the debug enabled, it will be used by express to be insanely verbose in the console: `export DEBUG='*'`
