### ISSUE TITLE
Parsing JSON webhook in Hubot - some fields print as [Object]

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#780]
I'm trying to use Hubot to parse the JSON output from a JIRA Webhook. I'm still learning Node, so I apologise if this is a basic issue and I'm missing something obvious.

I'm just using just dummy code at the moment, similar to what's mentioned in the docs for a [HTTP Listener](https://github.com/github/hubot/blob/d82e42c85a2ca40d76260280cd1019e851d74d99/docs/scripting.md#http-listener):

```
module.exports = (robot) ->
  robot.router.post '/jirawebhooks/fts-tickets', (req, res) ->
    console.dir("#{new Date()} jira webhook post_received")
    console.dir(req.body)
    console.dir(req.body.payload)
    console.dir(JSON.parse req.body)

    res.send 'OK'
```

Printing out `req.body` seems to work, except some fields are simply printed out as `[Object]`. I'm not entirely sure why:

```
'Wed Oct 01 2014 11:35:36 GMT+0000 (UTC) jira webhook post_received'
{ webhookEvent: 'jira:issue_updated',
  timestamp: 1412163338429,
  user:
   { self: 'https://jira.foobar.org/rest/api/2/user?username=victor.hooi',
     name: 'victor.hooi',
     emailAddress: 'victor.hooi@foobar.com',
     avatarUrls:
      { '16x16': 'https://jira.foobar.org/secure/useravatar?size=xsmall&ownerId=victor.hooi&avatarId=13400',
        '24x24': 'https://jira.foobar.org/secure/useravatar?size=small&ownerId=victor.hooi&avatarId=13400',
        '32x32': 'https://jira.foobar.org/secure/useravatar?size=medium&ownerId=victor.hooi&avatarId=13400',
        '48x48': 'https://jira.foobar.org/secure/useravatar?ownerId=victor.hooi&avatarId=13400' },
     displayName: 'Victor Hooi',
     active: true },
  issue:
   { id: '161211',
     self: 'https://jira.foobar.org/rest/api/2/issue/161211',
     key: 'BA-15424',
     fields:
      { summary: 'THIS IS A TEST TICKET',
        issuetype: [Object],
        customfield_10857: null,
        reporter: [Object],
...
```

The `req.body.payload` comes out as undefined, and attempting to `JSON.parse` the `req.body` gives me:

```
SyntaxError: Unexpected token o
  at Object.parse (native)
  at /home/ubuntu/foobar-glados/scripts/test_http_listener.coffee:6:12, <js>:7:24
  at callbacks (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/lib/router/index.js:161:37)
  at param (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/lib/router/index.js:135:11)
  at pass (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/lib/router/index.js:142:5)
  at Router._dispatch (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/lib/router/index.js:170:5)
  at Object.router (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/lib/router/index.js:33:10)
  at next (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:190:15)
  at multipart (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
  at /home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
  at urlencoded (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:48:27)
  at /home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
  at IncomingMessage.<anonymous> (/home/ubuntu/foobar-glados/node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/json.js:82:9)
  at IncomingMessage.emit (events.js:92:17)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
```

Is this because the body is already parsed at this point? I also noticed that I don't seem to have body-parser installed? I'd thought that Express had migrated to a separate body-parser package.

**Comment by technicalpickles** [comment]
> Is this because the body is already parsed at this point?

It should be, yeah.

> I also noticed that I don't seem to have body-parser installed? I'd thought that Express had migrated to a separate body-parser package.

It did, but to maintain compatibility with how hubot was working, we added this to the hubot default. The problem we keep running into is that it's not easy for hubot users to manipulate the express stack though, so there's discussion in https://github.com/github/hubot/issues/767 to extract it out of core.

**Comment by dreckguy** [comment]
bla

**Comment by bkeepers** [comment]
@victorhooi looks like your question was answered here. Let us know if you're still having issues though.
