### ISSUE TITLE
Setting brain value on 'loaded' - Maximum call stack exceeded

### ISSUE THREAD

**Issue by victorhooi** [github/hubot#880]
It's not mentioned in the official scripting documentation (https://github.com/github/hubot/blob/master/docs/scripting.md), however, it is mentioned elsewhere (http://www.icicletech.com/blog/automate-your-development-activities-with-hubot and http://thejacklawson.com/how-to-hubot/#/21) that you can use `robot.brain.on 'loaded', ->` to set variables when the Redis brain is ready.

I'm using the following snippet:

```
module.exports = (robot) ->

  robot.brain.on 'loaded', ->
    robot.brain.set 'aliases', {}

  robot.hear /alias set (\S*) (.*)/i, (msg) ->
    robot.brain.set aliases[msg.match[1]], msg.match[2]
    console.log(JSON.stringify(robot.brain.aliases))
    msg.reply("Alias set for " + msg.match[1])
```

and I get a `Maximum call stack exceeded` error when I try to start up Hubot:

```
[Fri Mar 13 2015 07:21:17 GMT+1100 (AEDT)] ERROR RangeError: Maximum call stack size exceeded
  at extend (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:155:3, <js>:149:67)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:30:5, <js>:34:7)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
  at Brain.emit (events.js:107:17)
  at Brain.set (/Users/victorhooi/foobar/foobar/foobar/node_modules/hubot/src/brain.coffee:31:5, <js>:35:12)
  at Brain.<anonymous> (/Users/victorhooi/foobar/foobar/foobar/scripts/example.coffee:15:5, <js>:4:26)
...
```

**Comment by michaelansel** [comment]
The problem here is that `set` for some reason emits a 'loaded' event (introduced [here](https://github.com/github/hubot/pull/447/files#diff-3f212f83b49bd9f3b418259c1f06c0cfR30)), but it isn't immediately obvious to me why that is needed. I'll keep digging (and asking @technicalpickles for context), but in the meantime you should be able work around the bug with something like this:

```coffeescript
firstTime = true
robot.brain.on 'loaded', ->
  if firstTime
    firstTime = false
    robot.set 'aliases', {}
```
