### ISSUE TITLE
Hubot should bubble up coffee script errors 

### ISSUE THREAD

**Issue by cycomachead** [github/hubot#992]
When I have a syntax error in a `.coffee` file, it's hard to debug using the normal stack trace. Using the `coffee` command (assuming I have it installed) yields better results. Would it be possible to bubble up more detailed coffee script errors, or is this a limitation of the way things are being loaded?

See this example for a recent case:

```
Michael at Yosemite-Pro in ~/Dropbox/Projects/CS10/Alonzo on master
$ ./alonzo 
Alonzo> [Fri Jun 26 2015 00:52:28 GMT-0700 (PDT)] ERROR Unable to load /Volumes/Michael/Users/Michael/Dropbox/Projects/CS10/Alonzo/scripts/meme: SyntaxError: unexpected {
  at Object.exports.throwSyntaxError (/Volumes/Michael/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
  at Object.parser.yy.parseError (/Volumes/Michael/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:265:20)
  at Object.parse (/Volumes/Michael/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/parser.js:537:22)
  at exports.compile.compile (/Volumes/Michael/Users/Michael/Dropbox/Projects/CS10/Alonzo/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:24)
  at Object.loadFile 
[... Omitted.]

Michael at Yosemite-Pro in ~/Dropbox/Projects/CS10/Alonzo on master*
$ coffee scripts/meme.coffee 
/Volumes/Michael/Users/Michael/Dropbox/Projects/CS10/Alonzo/scripts/meme.coffee:128:24: error: unexpected :
         top_left_y_pct: 0,
                       ^
```

**Comment by technicalpickles** [comment]
I think https://github.com/github/hubot/pull/900 might help with that
